### PR TITLE
Jenkinsfile: remove Fedora 34 and Ubuntu 21.10 "Impish", add Fedora 37

### PR DESCRIPTION
**Pull request by thaJeztah**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like some updates are needed for the SLES/OpenSUSE scripts; `createrepo` is no longer provided?

```
#31 [verify-packages 2/8] RUN . /root/.rpm-helpers; install_package createrepo
#31 sha256:2a4f1d9c47a241e657779268aab82bd68c98d9ec24a5d3df57ce6ed4f7f65671
#31 1.811 Loading repository data...
#31 2.618 Reading installed packages...
#31 3.267 'createrepo' not found in package names. Trying capabilities.
#31 3.267 No provider of 'createrepo' found.
#31 ERROR: executor failed running [/bin/sh -c . /root/.rpm-helpers; install_package createrepo]: exit code: 104
```

**Comment by thaJeztah** [comment]
Yup; on an older version of the image, it was still available;

<details>

```bash
docker run -it --rm docker.io/opensuse/leap:15
91717a2bb356:/ # zypper install createrepo
Retrieving repository 'Update repository of openSUSE Backports' metadata .............................................................................................................................[done]
Building repository 'Update repository of openSUSE Backports' cache ..................................................................................................................................[done]
Retrieving repository 'Non-OSS Repository' metadata -----------------------------------------------------------------------------------------------------------------------------------------------------[/]
Note: Received 1 new package signing key from repository Non-OSS Repository:

  Those additional keys are usually used to sign packages shipped by the repository. In order to
  validate those packages upon download and installation the new keys will be imported into the rpm
  database.

  New:
  Key Fingerprint:  4E98 E675 19D9 8DC7 362A 5990 E3A5 C360 307E 3D54
  Key Name:         SuSE Package Signing Key <build@suse.de>
  Key Algorithm:    RSA 1024
  Key Created:      Thu Mar 15 15:26:29 2018
  Key Expires:      Mon Mar 14 15:26:29 2022 (EXPIRED)
  Rpm Name:         gpg-pubkey-307e3d54-5aaa90a5

  The repository metadata introducing the new keys have been signed and validated by the trusted
  key:

  Repository:       Non-OSS Repository
  Key Fingerprint:  22C0 7BA5 3417 8CD0 2EFE 22AA B88B 2FD4 3DBD C284
  Key Name:         openSUSE Project Signing Key <opensuse@opensuse.org>
  Key Algorithm:    RSA 2048
  Key Created:      Mon May  5 08:37:40 2014
  Key Expires:      Thu May  2 08:37:40 2024
  Rpm Name:         gpg-pubkey-3dbdc284-53674dd4

Retrieving repository 'Non-OSS Repository' metadata ..................................................................................................................................................[done]
Building repository 'Non-OSS Repository' cache .......................................................................................................................................................[done]
Retrieving repository 'Main Repository' metadata .....................................................................................................................................................[done]
Building repository 'Main Repository' cache ..........................................................................................................................................................[done]
Retrieving repository 'Update repository with updates from SUSE Linux Enterprise 15' metadata ........................................................................................................[done]
Building repository 'Update repository with updates from SUSE Linux Enterprise 15' cache .............................................................................................................[done]
Retrieving repository 'Main Update Repository' metadata ..............................................................................................................................................[done]
Building repository 'Main Update Repository' cache ...................................................................................................................................................[done]
Retrieving repository 'Update Repository (Non-Oss)' metadata .........................................................................................................................................[done]
Building repository 'Update Repository (Non-Oss)' cache ..............................................................................................................................................[done]
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 36 NEW packages are going to be installed:
  createrepo dbus-1 deltarpm gio-branding-SLE girepository-1_0 glib2-tools libdb-4_8 libdbus-1-3 libexpat1 libgio-2_0-0 libgirepository-1_0-1 libgmodule-2_0-0 libgobject-2_0-0 libgthread-2_0-0
  libpython2_7-1_0 libxslt1 pkg-config python python-base python-gobject2 python-pyliblzma python-urlgrabber python-xml python2-cssselect python2-dbus-python python2-deltarpm python2-gobject python2-gpgme
  python2-iniparse python2-lxml python2-pycurl python2-rpm python2-six python2-yum shared-mime-info yum-metadata-parser

36 new packages to install.
Overall download size: 13.5 MiB. Already cached: 0 B. After the operation, additional 53.2 MiB will be used.
Continue? [y/n/v/...? shows all options] (y): y
Retrieving package deltarpm-3.6.1-3.19.x86_64                                                                                                                         (1/36), 211.6 KiB (818.7 KiB unpacked)
Retrieving: deltarpm-3.6.1-3.19.x86_64.rpm ...............................................................................................................................................[done (2.5 KiB/s)]
Retrieving package libdb-4_8-4.8.30-7.3.1.x86_64                                                                                                                      (2/36), 694.6 KiB (  3.1 MiB unpacked)
Retrieving: libdb-4_8-4.8.30-7.3.1.x86_64.rpm ........................................................................................................................................................[done]
Retrieving package libxslt1-1.1.32-3.8.24.x86_64                                                                                                                      (3/36), 139.8 KiB (340.3 KiB unpacked)
Retrieving: libxslt1-1.1.32-3.8.24.x86_64.rpm ........................................................................................................................................................[done]
Retrieving package pkg-config-0.29.2-1.436.x86_64                                                                                                                     (4/36), 231.6 KiB (675.4 KiB unpacked)
Retrieving: pkg-config-0.29.2-1.436.x86_64.rpm ...........................................................................................................................................[done (1.7 MiB/s)]
Retrieving package libdbus-1-3-1.12.2-8.11.2.x86_64                                                                                                                   (5/36), 150.3 KiB (325.9 KiB unpacked)
Retrieving: libdbus-1-3-1.12.2-8.11.2.x86_64.rpm .....................................................................................................................................................[done]
Retrieving package libexpat1-2.2.5-3.19.1.x86_64                                                                                                                      (6/36),  77.7 KiB (198.3 KiB unpacked)
Retrieving: libexpat1-2.2.5-3.19.1.x86_64.rpm ........................................................................................................................................................[done]
Retrieving package libgmodule-2_0-0-2.62.6-150200.3.9.1.x86_64                                                                                                        (7/36),  78.7 KiB ( 14.3 KiB unpacked)
Retrieving: libgmodule-2_0-0-2.62.6-150200.3.9.1.x86_64.rpm ..........................................................................................................................................[done]
Retrieving package libgobject-2_0-0-2.62.6-150200.3.9.1.x86_64                                                                                                        (8/36), 195.8 KiB (368.8 KiB unpacked)
Retrieving: libgobject-2_0-0-2.62.6-150200.3.9.1.x86_64.rpm ..............................................................................................................................[done (2.5 MiB/s)]
Retrieving package libgthread-2_0-0-2.62.6-150200.3.9.1.x86_64                                                                                                        (9/36),  75.6 KiB (  6.0 KiB unpacked)
Retrieving: libgthread-2_0-0-2.62.6-150200.3.9.1.x86_64.rpm ..........................................................................................................................................[done]
Retrieving package libpython2_7-1_0-2.7.18-150000.41.1.x86_64                                                                                                        (10/36), 841.6 KiB (  2.2 MiB unpacked)
Retrieving: libpython2_7-1_0-2.7.18-150000.41.1.x86_64.rpm ...........................................................................................................................................[done]
Retrieving package shared-mime-info-1.12-3.3.1.x86_64                                                                                                                (11/36), 364.5 KiB (  4.8 MiB unpacked)
Retrieving: shared-mime-info-1.12-3.3.1.x86_64.rpm ...................................................................................................................................................[done]
Retrieving package dbus-1-1.12.2-8.11.2.x86_64                                                                                                                       (12/36), 249.2 KiB (624.3 KiB unpacked)
Retrieving: dbus-1-1.12.2-8.11.2.x86_64.rpm ..............................................................................................................................................[done (1.1 MiB/s)]
Retrieving package python-base-2.7.18-150000.41.1.x86_64                                                                                                             (13/36),   5.8 MiB ( 23.5 MiB unpacked)
Retrieving: python-base-2.7.18-150000.41.1.x86_64.rpm ....................................................................................................................................[done (4.0 MiB/s)]
Retrieving package gio-branding-SLE-15-150300.19.3.1.noarch                                                                                                          (14/36),  17.4 KiB (  8.1 KiB unpacked)
Retrieving: gio-branding-SLE-15-150300.19.3.1.noarch.rpm .............................................................................................................................................[done]
Retrieving package python2-six-1.14.0-12.1.noarch                                                                                                                    (15/36),  33.8 KiB ( 78.8 KiB unpacked)
Retrieving: python2-six-1.14.0-12.1.noarch.rpm .......................................................................................................................................................[done]
Retrieving package python2-rpm-4.14.3-150300.46.1.x86_64                                                                                                             (16/36),  56.0 KiB (197.3 KiB unpacked)
Retrieving: python2-rpm-4.14.3-150300.46.1.x86_64.rpm ................................................................................................................................................[done]
Retrieving package python2-cssselect-1.0.3-150000.3.3.1.noarch                                                                                                       (17/36),  37.7 KiB (162.6 KiB unpacked)
Retrieving: python2-cssselect-1.0.3-150000.3.3.1.noarch.rpm ..........................................................................................................................................[done]
Retrieving package python-xml-2.7.18-150000.41.1.x86_64                                                                                                              (18/36), 212.8 KiB (910.9 KiB unpacked)
Retrieving: python-xml-2.7.18-150000.41.1.x86_64.rpm .....................................................................................................................................[done (3.3 KiB/s)]
Retrieving package python-2.7.18-150000.41.1.x86_64                                                                                                                  (19/36), 336.2 KiB (  1.4 MiB unpacked)
Retrieving: python-2.7.18-150000.41.1.x86_64.rpm .....................................................................................................................................................[done]
Retrieving package glib2-tools-2.62.6-150200.3.9.1.x86_64                                                                                                            (20/36), 167.3 KiB (308.4 KiB unpacked)
Retrieving: glib2-tools-2.62.6-150200.3.9.1.x86_64.rpm ...............................................................................................................................................[done]
Retrieving package libgio-2_0-0-2.62.6-150200.3.9.1.x86_64                                                                                                           (21/36), 640.1 KiB (  1.8 MiB unpacked)
Retrieving: libgio-2_0-0-2.62.6-150200.3.9.1.x86_64.rpm ..............................................................................................................................................[done]
Retrieving package python2-lxml-4.7.1-3.7.1.x86_64                                                                                                                   (22/36),   1.1 MiB (  4.2 MiB unpacked)
Retrieving: python2-lxml-4.7.1-3.7.1.x86_64.rpm ......................................................................................................................................................[done]
Retrieving package python2-pycurl-7.43.0.2-4.3.1.x86_64                                                                                                              (23/36),  87.8 KiB (251.0 KiB unpacked)
Retrieving: python2-pycurl-7.43.0.2-4.3.1.x86_64.rpm .................................................................................................................................................[done]
Retrieving package python2-gpgme-0.3-2.38.x86_64                                                                                                                     (24/36),  60.2 KiB (187.3 KiB unpacked)
Retrieving: python2-gpgme-0.3-2.38.x86_64.rpm ........................................................................................................................................................[done]
Retrieving package python2-deltarpm-3.6.1-3.19.x86_64                                                                                                                (25/36),  64.9 KiB (107.2 KiB unpacked)
Retrieving: python2-deltarpm-3.6.1-3.19.x86_64.rpm ...................................................................................................................................................[done]
Retrieving package python-pyliblzma-0.5.3-1.35.x86_64                                                                                                                (26/36),  32.0 KiB ( 66.9 KiB unpacked)
Retrieving: python-pyliblzma-0.5.3-1.35.x86_64.rpm .......................................................................................................................................[done (3.5 KiB/s)]
Retrieving package python2-iniparse-0.5-1.25.noarch                                                                                                                  (27/36),  41.3 KiB (160.5 KiB unpacked)
Retrieving: python2-iniparse-0.5-1.25.noarch.rpm .....................................................................................................................................................[done]
Retrieving package yum-metadata-parser-1.1.2-1.29.x86_64                                                                                                             (28/36),  28.2 KiB ( 62.1 KiB unpacked)
Retrieving: yum-metadata-parser-1.1.2-1.29.x86_64.rpm ................................................................................................................................................[done]
Retrieving package python-gobject2-2.28.7-1.27.x86_64                                                                                                                (29/36), 291.0 KiB (  1.2 MiB unpacked)
Retrieving: python-gobject2-2.28.7-1.27.x86_64.rpm ...................................................................................................................................................[done]
Retrieving package libgirepository-1_0-1-1.62.0-2.28.x86_64                                                                                                          (30/36), 111.4 KiB (240.7 KiB unpacked)
Retrieving: libgirepository-1_0-1-1.62.0-2.28.x86_64.rpm .............................................................................................................................................[done]
Retrieving package girepository-1_0-1.62.0-2.28.x86_64                                                                                                               (31/36), 171.3 KiB (694.3 KiB unpacked)
Retrieving: girepository-1_0-1.62.0-2.28.x86_64.rpm ......................................................................................................................................[done (1.1 KiB/s)]
Retrieving package python-urlgrabber-3.9.1-1.37.noarch                                                                                                               (32/36),  78.2 KiB (297.4 KiB unpacked)
Retrieving: python-urlgrabber-3.9.1-1.37.noarch.rpm ..................................................................................................................................................[done]
Retrieving package python2-gobject-3.34.0-2.27.x86_64                                                                                                                (33/36), 396.2 KiB (  1.3 MiB unpacked)
Retrieving: python2-gobject-3.34.0-2.27.x86_64.rpm ...................................................................................................................................................[done]
Retrieving package python2-dbus-python-1.2.16-6.3.1.x86_64                                                                                                           (34/36), 123.6 KiB (493.2 KiB unpacked)
Retrieving: python2-dbus-python-1.2.16-6.3.1.x86_64.rpm ..............................................................................................................................................[done]
Retrieving package python2-yum-3.4.3-5.8.1.x86_64                                                                                                                    (35/36), 429.5 KiB (  1.9 MiB unpacked)
Retrieving: python2-yum-3.4.3-5.8.1.x86_64.rpm ...........................................................................................................................................[done (3.5 KiB/s)]
Retrieving package createrepo-0.10.4-bp153.1.12.x86_64                                                                                                               (36/36),  93.0 KiB (320.7 KiB unpacked)
Retrieving: createrepo-0.10.4-bp153.1.12.x86_64.rpm ..................................................................................................................................................[done]

Checking for file conflicts: .........................................................................................................................................................................[done]
( 1/36) Installing: deltarpm-3.6.1-3.19.x86_64 .......................................................................................................................................................[done]
( 2/36) Installing: libdb-4_8-4.8.30-7.3.1.x86_64 ....................................................................................................................................................[done]
( 3/36) Installing: libxslt1-1.1.32-3.8.24.x86_64 ....................................................................................................................................................[done]
( 4/36) Installing: pkg-config-0.29.2-1.436.x86_64 ...................................................................................................................................................[done]
( 5/36) Installing: libdbus-1-3-1.12.2-8.11.2.x86_64 .................................................................................................................................................[done]
( 6/36) Installing: libexpat1-2.2.5-3.19.1.x86_64 ....................................................................................................................................................[done]
( 7/36) Installing: libgmodule-2_0-0-2.62.6-150200.3.9.1.x86_64 ......................................................................................................................................[done]
( 8/36) Installing: libgobject-2_0-0-2.62.6-150200.3.9.1.x86_64 ......................................................................................................................................[done]
( 9/36) Installing: libgthread-2_0-0-2.62.6-150200.3.9.1.x86_64 ......................................................................................................................................[done]
(10/36) Installing: libpython2_7-1_0-2.7.18-150000.41.1.x86_64 .......................................................................................................................................[done]
(11/36) Installing: shared-mime-info-1.12-3.3.1.x86_64 ...............................................................................................................................................[done]
/var/tmp/rpm-tmp.5ZM24l: line 34: [: : integer expression expected
update-alternatives: using /usr/bin/dbus-launch.nox11 to provide /usr/bin/dbus-launch (dbus-launch) in auto mode
(12/36) Installing: dbus-1-1.12.2-8.11.2.x86_64 ......................................................................................................................................................[done]
(13/36) Installing: python-base-2.7.18-150000.41.1.x86_64 ............................................................................................................................................[done]
(14/36) Installing: gio-branding-SLE-15-150300.19.3.1.noarch .........................................................................................................................................[done]
(15/36) Installing: python2-six-1.14.0-12.1.noarch ...................................................................................................................................................[done]
(16/36) Installing: python2-rpm-4.14.3-150300.46.1.x86_64 ............................................................................................................................................[done]
(17/36) Installing: python2-cssselect-1.0.3-150000.3.3.1.noarch ......................................................................................................................................[done]
(18/36) Installing: python-xml-2.7.18-150000.41.1.x86_64 .............................................................................................................................................[done]
(19/36) Installing: python-2.7.18-150000.41.1.x86_64 .................................................................................................................................................[done]
No schema files found: doing nothing.
(20/36) Installing: glib2-tools-2.62.6-150200.3.9.1.x86_64 ...........................................................................................................................................[done]
No schema files found: doing nothing.
(21/36) Installing: libgio-2_0-0-2.62.6-150200.3.9.1.x86_64 ..........................................................................................................................................[done]
(22/36) Installing: python2-lxml-4.7.1-3.7.1.x86_64 ..................................................................................................................................................[done]
(23/36) Installing: python2-pycurl-7.43.0.2-4.3.1.x86_64 .............................................................................................................................................[done]
(24/36) Installing: python2-gpgme-0.3-2.38.x86_64 ....................................................................................................................................................[done]
(25/36) Installing: python2-deltarpm-3.6.1-3.19.x86_64 ...............................................................................................................................................[done]
(26/36) Installing: python-pyliblzma-0.5.3-1.35.x86_64 ...............................................................................................................................................[done]
(27/36) Installing: python2-iniparse-0.5-1.25.noarch .................................................................................................................................................[done]
(28/36) Installing: yum-metadata-parser-1.1.2-1.29.x86_64 ............................................................................................................................................[done]
(29/36) Installing: python-gobject2-2.28.7-1.27.x86_64 ...............................................................................................................................................[done]
(30/36) Installing: libgirepository-1_0-1-1.62.0-2.28.x86_64 .........................................................................................................................................[done]
(31/36) Installing: girepository-1_0-1.62.0-2.28.x86_64 ..............................................................................................................................................[done]
(32/36) Installing: python-urlgrabber-3.9.1-1.37.noarch ..............................................................................................................................................[done]
(33/36) Installing: python2-gobject-3.34.0-2.27.x86_64 ...............................................................................................................................................[done]
(34/36) Installing: python2-dbus-python-1.2.16-6.3.1.x86_64 ..........................................................................................................................................[done]
(35/36) Installing: python2-yum-3.4.3-5.8.1.x86_64 ...................................................................................................................................................[done]
update-alternatives: using /usr/bin/createrepo_yum to provide /usr/bin/createrepo (createrepo) in auto mode
(36/36) Installing: createrepo-0.10.4-bp153.1.12.x86_64 ..............................................................................................................................................[done]
Executing %posttrans scripts .........................................................................................................................................................................[done]
```

</details>


But after pulling a fresh version, it's no longer there;

```bash
$ docker pull docker.io/opensuse/leap:15
15: Pulling from opensuse/leap
847758cbac64: Pull complete
Digest: sha256:e8c12f20d75d09bc591bf218e31cb94d3d6f425b641276ebbfc6c5d62063a2ec
Status: Downloaded newer image for opensuse/leap:15
docker.io/opensuse/leap:15

$ docker run -it --rm docker.io/opensuse/leap:15
1bdad208e62a:/ # zypper install createrepo
Retrieving repository 'Update repository of openSUSE Backports' metadata .............................................................................................................................[done]
Building repository 'Update repository of openSUSE Backports' cache ..................................................................................................................................[done]
Retrieving repository 'Non-OSS Repository' metadata ..................................................................................................................................................[done]
Building repository 'Non-OSS Repository' cache .......................................................................................................................................................[done]
Retrieving repository 'Main Repository' metadata .....................................................................................................................................................[done]
Building repository 'Main Repository' cache ..........................................................................................................................................................[done]
Retrieving repository 'Update repository with updates from SUSE Linux Enterprise 15' metadata ........................................................................................................[done]
Building repository 'Update repository with updates from SUSE Linux Enterprise 15' cache .............................................................................................................[done]
Retrieving repository 'Main Update Repository' metadata ..............................................................................................................................................[done]
Building repository 'Main Update Repository' cache ...................................................................................................................................................[done]
Retrieving repository 'Update Repository (Non-Oss)' metadata .........................................................................................................................................[done]
Building repository 'Update Repository (Non-Oss)' cache ..............................................................................................................................................[done]
Loading repository data...
Reading installed packages...
'createrepo' not found in package names. Trying capabilities.
No provider of 'createrepo' found.
Resolving package dependencies...
Nothing to do.
```

**Comment by thaJeztah** [comment]
Looks like the package was renamed; now 2 flavours available; a `C` implementation and a Python implementation?

```bash
zypper search createrepo
Loading repository data...
Reading installed packages...

S | Name                  | Summary                                        | Type
--+-----------------------+------------------------------------------------+--------
  | createrepo_c          | RPM repository metadata generation utility     | package
  | libcreaterepo_c-devel | Library for repodata manipulation              | package
  | libcreaterepo_c0      | Library for repodata manipulation              | package
  | python3-createrepo_c  | Python 3 bindings for the createrepo_c library | package
```

**Comment by thaJeztah** [comment]
opened https://github.com/docker/containerd-packaging/pull/289 to fix/workaraound that

**Review by rumpl — DISMISSED** [review]

**Comment by thaJeztah** [comment]
All green now; merging

**Pull request merged**
