### PR TITLE
rpm: add support for building on CentOS 8

### PR DESCRIPTION
**Pull request by thaJeztah**
replaces https://github.com/docker/containerd-packaging/pull/118

### CODE REVIEW

**Comment by thaJeztah** [comment]
@silvin-lubecki  @seemethere @crosbymichael @cpuguy83 PTAL

**Comment by crosbymichael** [comment]
LGTM

**Comment by thaJeztah** [comment]
Failure on arm64;

```
+ dnf -y install make gcc systemd libseccomp-devel
Last metadata expiration check: 0:00:37 ago on Mon Mar 23 20:30:48 2020.
Package systemd-239-18.el8_1.1.aarch64 is already installed.
No match for argument: libseccomp-devel
Error: Unable to find a match: libseccomp-devel
Makefile:64: recipe for target 'build' failed
make: *** [build] Error 1
```

Looks like for arm64 it's in the PowerTools repo; https://centos.pkgs.org/8/centos-appstream-x86_64/libseccomp-devel-2.4.1-1.el8.x86_64.rpm.html

Arm32 images don't seem to be available, so I'll disable that

**Comment by thaJeztah** [comment]
ok, updated;

- disabled builds for arm32, because no image exists for CentOS 8 (arm32)
- enabled the PowerTools repository so that (hopefully) arm64 completes successfully
- removed obsolete `sed` for arm64

**Pull request merged**
