### PR TITLE
Jenkinsfile: remove Ubuntu 20.10 "Groovy" (EOL: 2021-07-22)

### PR DESCRIPTION
**Pull request by thaJeztah**

### CODE REVIEW

**Review by StefanScherer — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Looks like Jenkins didn't run on this; let me try if close/reopen works

**Comment by thaJeztah** [comment]
nope. doesn't trigger for some reason

**Comment by StefanScherer** [comment]
I've changed the role of the Jenkins user for this pipeline and retriggered a scan for PRs. It started building now.

**Comment by thaJeztah** [comment]
Thanks! I recalled containerd master was broken with our build scripts, so was expecting to see Jenkins fail (which is why I noticed it didn't run).

Now, next step will be to fix upstream containerd to be buildable again (I think it started to require the `git` repository to be part of the build-source 😞)

**Comment by thaJeztah** [comment]
This one looks to be something different than I thought; containerd main branch is broken; https://github.com/containerd/containerd/issues/6016

**Comment by thaJeztah** [comment]
OK; now looks a lot better; the Fedora Rawhide failure is (currently) expected, so can be ignored


@StefanScherer @fredericdalleau PTAL

**Review by StefanScherer — APPROVED** [review]
LGTM

**Pull request merged**
