### PR TITLE
Archive windows artifacts

### PR DESCRIPTION
**Pull request by StefanScherer**
This PR archives the Windows artifacts as well.

### CODE REVIEW

**Comment by StefanScherer** [comment]
Well, first attempt failed:
```
Archiving artifacts
‘build/windows/*.zip’ doesn’t match anything: ‘build’ exists but not ‘build/windows/*.zip’
No artifacts found that match the file pattern "build/windows/*.zip". Configuration error?
```

Replaced the `build/windows/*.zip` with `build/windows/containerd.zip`. 🤞

**Comment by thaJeztah** [comment]
> Well, first attempt failed:

Oh! I think Windows was still failing due to the missing `.exe` extension on master since we reverted https://github.com/docker/containerd-packaging/pull/131

Still need to look at https://github.com/docker/containerd-packaging/pull/131#issuecomment-579879745 to see if we can backport those changes in the containerd 1.2 branch (so that the build-scripts work _both_ on master _and_ on the 1.2, 1.3 release branches

**Comment by silvin-lubecki** [comment]
@StefanScherer this PR needs a rebase 🐯

**Comment by StefanScherer** [comment]
@silvin-lubecki I've rebased, thanks for the reminder :-)

**Comment by thaJeztah** [comment]
ok, still failing (on the `.exe` thing?)

```
Powershell.exe New-Item -ItemType Directory -Force -Path build/windows/


    Directory: D:\jenkins\workspace\containerd-packaging_PR-139\build


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----        4/22/2020  10:13 AM                windows                                                               


docker run \
	--rm \
	-v "d:/jenkins/workspace/containerd-packaging_PR-139/src/:C:/gopath/src" \
	-v "d:/jenkins/workspace/containerd-packaging_PR-139/build/windows:C:/gopath/src/github.com/containerd/containerd/bin" \
	-w "C:/gopath/src/github.com/containerd/containerd" \
	dockereng/containerd-windows-builder \
	make bin/containerd
+ bin/containerd
Powershell.exe New-Item -ItemType Directory -Force -Path build/windows/


    Directory: D:\jenkins\workspace\containerd-packaging_PR-139\build


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----        4/22/2020  10:13 AM                windows                                                               


docker run \
	--rm \
	-v "d:/jenkins/workspace/containerd-packaging_PR-139/src/:C:/gopath/src" \
	-v "d:/jenkins/workspace/containerd-packaging_PR-139/build/windows:C:/gopath/src/github.com/containerd/containerd/bin" \
	-w "C:/gopath/src/github.com/containerd/containerd" \
	dockereng/containerd-windows-builder \
	make bin/ctr
+ bin/ctr
Powershell.exe Compress-Archive -Force -Path 'build/windows/*.exe' -DestinationPath 'build/windows/containerd.zip'
```

```
Archiving artifacts
‘build/windows/containerd.zip’ doesn’t match anything: ‘build’ exists but not ‘build/windows/containerd.zip’
No artifacts found that match the file pattern "build/windows/containerd.zip". Configuration error?
```

**Comment by StefanScherer** [comment]
Yes, no `.exe` means no files to zip which means no `.zip` and then archiving the zip fails.

**Comment by StefanScherer** [comment]
I've tried the build on a windows-2019 machine both with containerd master branch as well as v1.2.13 tag.

It fails with the 1.2.x tag, so I guess we need to backport https://github.com/containerd/containerd/pull/3823
and then add https://github.com/docker/containerd-packaging/pull/128 again.

I did that manually on the build machine and the build for 1.2.13 would work with both applied.

**Comment by StefanScherer** [comment]
I've opened https://github.com/containerd/containerd/pull/4205

**Pull request closed without merging**
