### PR TITLE
deb, rpm: use GOTOOLCHAIN=local

### PR DESCRIPTION
**Pull request by thaJeztah**
- relates to https://github.com/docker-library/golang/issues/472

Make sure we don't get unexpected updates of the go toolchain when building.

### CODE REVIEW

**Review by sam-thibault — APPROVED** [review]

**Review by rumpl — APPROVED** [review]

**Comment by thaJeztah** [comment]
Looks like Jenkins is failing, but I don't have access (I recall @neersighted was looking into that at some point, but don't know where we ended on)

**Comment by crazy-max** [comment]
> /cc @crazy-max in case similar changes are needed in docker/packaging as well 🤔

Thanks for the ping, will do

**Comment by thaJeztah** [comment]
@crazy-max FWIW; official  images will set this as a default as well (at least in new builds), but if we have parts of the pipeline that are _not_ using `FROM golang`, and (like in this repository) installing `go` in another image, that env-var won't be set. In that case, we need some changes probably  (and set the env-var)

**Pull request merged**
