### PR TITLE
Jenkinsfile: enable s390x builds for Ubuntu Focal

### PR DESCRIPTION
**Pull request by thaJeztah**
follow-up to https://github.com/docker/containerd-packaging/pull/167

### CODE REVIEW

**Comment by tiborvass** [comment]
@thaJeztah do we also need this for 19.03?

**Comment by thaJeztah** [comment]
@tiborvass not strictly needed; this only enables the builds in this repository, but the "release packaging" pipeline decides what gets built. It doesn't hurt to enable it here so that we can run CI and catch issues early

**Comment by thaJeztah** [comment]
@tiborvass PTAL

**Comment by thaJeztah** [comment]
closing this for now

**Pull request closed without merging**
